name: Chore
description: Zadanie techniczne (refaktoryzacja, aktualizacja)
title: "chore: [krótki opis]"
labels: ["type:chore","P3-low"]
body:
  - type: input
    id: summary
    attributes:
      label: Opis
